# -*- coding: utf-8 -*-
"""child mortality rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mtLnA9waputmxI0OJQQwwtv-4PoL7d9c
"""

import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/data science project/data/child-mortality.csv")
df.head()

df = df[(df["Year"] >= 1957) & (df["Year"] <= 2023)]

countries = ["United States", "Japan", "China", "India", "Brazil", "Nigeria", "Ethiopia"]

df_plot = df[df["Entity"].isin(countries)]

fig = px.line(
    df_plot,
    x="Year",
    y="Child mortality rate",
    color="Entity",
    title="Child Mortality Rate (1957–2023): Selected Countries",
    labels={
        "Year": "Year",
        "Child mortality rate": "Child Mortality Rate (per 1,000 live births)",
        "Entity": "Country"
    }
)

fig.update_layout(
    width=900,
    height=550,
    legend_title_text="Country"
)

fig.show()

fig.write_html("mortality_rate.html")

df = pd.read_csv("/content/drive/MyDrive/data science project/data/child-mortality-gdp-per-capita.csv")
df.head()

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/data science project/data/child-mortality-gdp-per-capita.csv")

df = df[df["Year"] == 2020]
df = df[df["Code"].notna()]
df = df[df["Child mortality rate"].notna()]
df = df[df["GDP per capita"].notna()]

for col in ["GDP per capita", "Child mortality rate"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df[df["GDP per capita"] > 0]

fig = px.scatter(
    df,
    x="GDP per capita",
    y="Child mortality rate",
    hover_name="Entity",
    opacity=0.7,
    size_max=12,
    title="Child Mortality Rate vs GDP per capita (2020)",
    labels={
        "GDP per capita": "GDP per capita (log scale)",
        "Child mortality rate": "Child mortality rate",
    },
)

fig.update_xaxes(type="log")

fig.update_layout(
    width=900,
    height=600
)

fig.show()

print(len(df))
print(df["GDP per capita"])

fig.write_html("mortality_GDP.html")

import statsmodels.api as sm
x = df["GDP per capita"]
y = df["Child mortality rate"]
X_log = np.log(x)
X_log_const = sm.add_constant(X_log)
model = sm.OLS(y, X_log_const).fit()

print(model.summary())

import plotly.graph_objects as go

x = df["GDP per capita"]
y = df["Child mortality rate"]

X_log = np.log(x)
X_log_const = sm.add_constant(X_log)
model = sm.OLS(y, X_log_const).fit()

print(model.summary())


x_sorted = np.sort(x)
X_log_sorted = sm.add_constant(np.log(x_sorted))
y_pred = model.predict(X_log_sorted)

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=x,
    y=y,
    mode="markers",
    name="Countries",
    marker=dict(size=8, opacity=0.6)
))


fig.add_trace(go.Scatter(
    x=x_sorted,
    y=y_pred,
    mode="lines",
    name="Regression line",
    line=dict(color="red", width=2)
))

fig.update_xaxes(type="log", title_text="GDP per capita")
fig.update_yaxes(title_text="Child mortality rate")

fig.update_layout(
    title="Child Mortality vs GDP per capita (Regression)",
    width=900,
    height=600,
    legend_title_text="Legend"
)

fig.show()

fig.write_html("mortality_regression.html")